sudo: false
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev

language: rust
rust:
  - nightly
  - beta
  - stable

before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH

script:
  - |
      travis-cargo build &&
      travis-cargo test &&
      travis-cargo bench &&
      travis-cargo --only stable doc

after_success:
  - travis-cargo --only stable doc-upload
  - travis-cargo coveralls --no-sudo --verify

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=" "
    - secure: "ySW1tffk3YRjoP5oi7yHgZyu/yiEPVppLK943c2csym05Scb8dLfgJKWY45kKpddf3hC8ZVVSwVIIuW7Jl6cnlAXv87awGvq/GG4HTaRbXeE7tNKBbyC8Pb2M7I1bICCqEV4EM/BxYFx/AB+BEfmcKlvi1by2fjFlKSeCGCnozZFjRJ6ai6a+IpP5T79IlfcAJytok6jFPkpSBez70TXQ02gCBhaLornS5Tw/X4RweQy9rVesw2kXMiIwg7DvEKgjviFEEKogKg/j5h9ik0ZOUk90jdDxF9glVZigOcAuXy3kAKQvJM9V5egLlCXAiz1nVrA5wF5hiYcqPCKB0VGv866qgnx7T+s2dqQqOFLbqYNB80m/REMfjV0pgpjh6O3+WQho1UDf5nLdPLTmuDt/F8BK9VUH/WQKX8yACxFKCWAu3zh/h/e8zWn0FYEIRBW36aQC3kPmR/nXxOwHCGzqqcBANiKKK38PInV4hXvyhWf+HRAO/PgQ3MxKxLjc4XIgNsXd670cbi7HR6eBFtTHFw0nQUrvP0V41XrhNqPcVWJMLzc0XyWODthzAjU44ubm32kDVMFImQBuYNfwBgXmIyCXhc8O+DlYbZURrD8Eih22t90u1bLR/Box1y44THJDRqUrSrDvgup1bP3/hIkzBYOmEh4MGh5BCtnO4dThE8="

notifications:
  email: false
